# sources: KXTV https://www.abc10.com/article/news/nation-world/daylight-saving-time-bill-status-all-50-states/507-25ff8777-63bc-423f-895d-22f5a3d5d28c
# as of 2021-11
# 4 never observed 3 passed 2 pending 1 failed/stalled 0 no consideration
legislation = {
        'alabama':              3,
        'alaska':               2,
        'arizona':              4,
        'arkansas':             1,
        'california':           1,
        'colorado':             1,
        'connecticut':          1,
        'delaware':             3,
        'district of columbia': -1,
        'florida':              3,
        'georgia':              3,
        'hawaii':               4,
        'idaho':                3,
        'illinois':             2,
        'indiana':              -1,
        'iowa':                 2,
        'kansas':               1,
        'kentucky':             1,
        'louisiana':            3,
        'maine':                3,
        'maryland':             1,
        'massachusetts':        1,
        'michigan':             2,
        'minnesota':            3,
        'mississippi':          3,
        'missouri':             2,
        'montana':              3,
        'nebraska':             2,
        'nevada':               1,
        'new hampshire':        1,
        'new jersey':           2,
        'new mexico':           1,
        'new york':             1,
        'north carolina':       2,
        'north dakota':         1,
        'ohio':                 2,
        'oklahoma':             1,
        'oregon':               3,
        'pennsylvania':         2,
        'puerto rico':          -1,
        'rhode island':         -1,
        'south carolina':       3,
        'south dakota':         1,
        'tennessee':            3,
        'texas':                2,
        'utah':                 3,
        'vermont':              1,
        'virginia':             2,
        'washington':           3,
        'west virginia':        1,
        'wisconsin':            1,
        'wyoming':              3,
}
